# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Malina Malina
email: malina.randrianavony@gmail.com
description:
  I am Malina Randrianavony, an engineer by trade, designer at â™¥ and artist
  on occasions who believes magic happens at the intersection of functionality,
  beauty and meaning.
baseurl: ""

url: "http://designesse.github.io/malina_2018"

github_username: designesse

include: ["_pages"]

collections:
  pages:
    output: true
    permalink: /:path/
  logos:

sass:
  sass_dir: assets/css
